version: '3.8'

services:
  postgres:
    image: postgres:17.2-alpine
    container_name: workoutdata-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: workout_user
      POSTGRES_PASSWORD: workout_password
      POSTGRES_DB: workout_data
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - workout_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workout_user -d workout_data"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  workout_network:
    driver: bridge
